name: billing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+3
  logger: ^2.5.0
  intl: ^0.20.1
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_launcher_icons: ^0.14.2
  rename_app: ^1.6.1
  sqflite: ^2.4.2
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - Assets/icons/
    - Assets/
    - Assets/images/
    - Assets/images/stamp.png
    - assets/images/nagerbazar_invoice-1.png
